### ISSUE TITLE
Multi-multi compare

### ISSUE THREAD

**Issue by HaoBytes** [eaclark07/sms#7]
Hi!
Thank you for your amazing work!

Is it possible compare multi-to-multi sentences?
if yes, what is inputs looks like?

Thanks!

**Comment by HaoBytes** [comment]
And when I running the model, I get this. how could I define inputs file, would you like to give me example? Thank you very much!
```
(SMS) cspc402:wmd-relax-master m32815hl$ python smd.py input.tsv elmo sms
[nltk_data] Downloading package stopwords to /Users/user/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /Users/user/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
/Users/user/opt/anaconda3/envs/SMS/lib/python3.6/site-packages/sklearn/utils/linear_assignment_.py:22: FutureWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  FutureWarning)
loading spacy
Found 1 documents
0% done with calculations
```

**Comment by HaoBytes** [comment]
update my inputs are 

> "Politician speaks to the media in Illinois."
> "The president greets the press in Chicago."

```
loading spacy
Found 2 documents
Traceback (most recent call last):
  File "smd.py", line 238, in <module>
    calc_smd(in_f, out_f)
  File "smd.py", line 194, in calc_smd
    token_doc_list, text_doc_list = tokenize_texts(inLines)
  File "smd.py", line 35, in tokenize_texts
    text = doc.split('\t')[i].strip()
IndexError: list index out of range
```

**Comment by HaoBytes** [comment]
Sorted thanks
